
project_id = "ddoxkwmwbxcagnrmwygo"
[functions.generate-summary]
verify_jwt = false
[functions.transcribe-audio]
verify_jwt = false
[functions.send-invite]
verify_jwt = false
[functions.text-to-speech]
verify_jwt = false
