// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddoxkwmwbxcagnrmwygo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkb3hrd213YnhjYWducm13eWdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU3OTUxMTcsImV4cCI6MjA1MTM3MTExN30.N1TotJZZO-TI-Vt-IBn5Wko1etnYDzWqVCwaqTMI33o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);